language: java
install: mvn install -s support/settings.xml -DskipTests=true -P,-version
script: mvn test -s support/settings.xml -P,-version
after_success: mvn deploy -s support/settings.xml -DskipTests=true -P,-version
jdk:
  - oraclejdk7
  - openjdk7

branches:
  only:
    - travis
env:
  global:
    - secure: "O17SbSk/7px/ZOe288D2nUclGKf7MOM91esmmaVyBxHkr4EMcVy55JaPxvYlfm7B31EKkCFyZ98A6bnR+ORoW9BU+nvbLd4jrZanRM7bD4Z5vaDMKmgEdFLUICULGplTweMKB2LjSxzfgJDqVyPq/t+rOL/wvWO9zPrpEmcS8aU="
    - secure: "N0YX2bmsQ7+i/jTnc5sPcjXXaCoyMuqKgr5RA9kWNMy8kktXm68G2Yvdqal8AKfBoRoUHrHuBtYIUx6GC16uF9S4tUCMS0Orzi02gRI7CpdyhLMrOHTtWQMhq5NKTy52+6tllXjw7kE99GCfUZMeVwyCMDxi8+NjNmj5Xhu6k4w="

notifications:
  irc: "irc.freenode.org#dynjs"
